--- #installation of jenkins
- hosts: FEservers
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh
  tasks:
  - name: Installing Java version 1.8-openjdk
    yum:
      name: java-1.8.0-openjdk
      state: present
  - name: Download Jenkins repo
    get_url:
      url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
  - name: Import a key from URL
    rpm_key:
      state: present
      key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
  - name: Install Jenkins
    yum:
      name: jenkins
      state: latest
    notify:
    - enable and start jenkins service
  handlers:
  - name: enable and start jenkins service
    service:
      name: jenkins
      enabled: yes
      state: restarted
